### ISSUE TITLE
Test Utils Roadmap

### ISSUE THREAD

**Issue by danielroe** [nuxt/test-utils#204]
```[tasklist]
### Tasks
- [x] Assign old Nuxt 2 issues `v0` label
- [ ] Move `@nuxt/test-utils` from https://github.com/nuxt/nuxt/tree/6141c08a44346c6753b4468932c91bc6fc830ed7/packages/test-utils to this repository
- [ ] Create new nightly release workflow in this repo
- [ ] Move `nuxt-vitest` into this repo
- [ ] Set up testing harness
```
