### ISSUE TITLE
Features Testing Checklist

### ISSUE THREAD

**Issue by antfu** [nuxt/test-utils#217]
A list to tracking the progress of tests for features, please feel free to add more

- [x] Dev SSR
- [x] Dev HMR
- [ ] Lazy components with loader @antfu 
- [x] Relative assets: https://github.com/nuxt/nuxt.js/issues/13426
- [x] E2E Tests for console.error
