### ISSUE TITLE
Test Utils Roadmap

### ISSUE THREAD

**Issue by danielroe** [nuxt/test-utils#434]
```[tasklist]
### Tasks
- [x] Assign old Nuxt 2 issues `v0` label
- [x] Move `@nuxt/test-utils` from https://github.com/nuxt/nuxt/tree/6141c08a44346c6753b4468932c91bc6fc830ed7/packages/test-utils to this repository
- [x] Create new nightly release workflow in this repo
- [x] Set up testing harness
- [x] Create README to orientate users
- [x] Move `nuxt-vitest` into this repo
- [ ] https://github.com/nuxt/nuxt/issues/22577
```
